packages:
  - "."
allowBuilds:
  sharp: false
  unrs-resolver: false
  prisma: true
  "@prisma/engines": true
  "@prisma/client": true
  '@firebase/util': false
  protobufjs: false
minimumReleaseAgeExclude:
  - ai@7.0.16
overrides:
  jose: 4.15.9
